databases:
  - name: experiment-hosting
    databaseName: experiment-hosting
    user: thewolfcommander

services:
  - type: web
    name: experiment-hosting
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: experiment-hosting
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4