databases:
  - name: experimentHosting
    databaseName: experimentHosting
    user: thewolfcommander

services:
  - type: web
    name: experimentHosting
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: experimentHosting
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4